apiVersion: v2
name: opentelemetry-demo-datadog
description: OpenTelemetry Demo Helm Chart for Datadog
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: datadog
    condition: ingest
    version: 3.3.0
    repository: https://helm.datadoghq.com
  - name: opentelemetry-demo
    version: 0.12.6
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
